stages:
  - build
  - test

workflow:
  rules:
    # Don't run CI on archived branches
    - if: $CI_COMMIT_BRANCH =~ /^archive\//
      when: never
    # From: https://docs.gitlab.com/ee/ci/yaml/workflow.html#switch-between-branch-pipelines-and-merge-request-pipelines
    # This does two things.
    # 1) Ensures all jobs are run for merge requests
    # 2) Prevents there being a pipeline triggered for a branch
    #    when there is an open merge request (a wasted double up)
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

default:
  tags:
    - 8-core

# Use a pre-built Docker image that includes the Zephyr build environment.
image: zephyrprojectrtos/zephyr-build:latest

variables:
  ZEPHYR_WORKSPACE: zephyrproject

.zephyr_setup: &zephyr_setup_template
  # Common setup steps for any Zephyr job
  before_script:
    # 1. Initialize the west workspace from upstream Zephyr manifest
    - west init -m https://github.com/zephyrproject-rtos/zephyr --mr main $ZEPHYR_WORKSPACE
    - cd $ZEPHYR_WORKSPACE
    # 2. Update all modules defined in the manifest (e.g., zephyr, modules)
    - west update
    # 3. Export Zephyr's CMake package and set up the environment
    - west zephyr-export
    # 4. Create and activate the virtual environment
    - python3 -m venv .venv
    - source .venv/bin/activate
    - export ZEPHYR_BASE=$PWD/zephyr

build:
  stage: build
  <<: *zephyr_setup_template
  script:
    # -p auto: automatically handles pristine builds
    - west build -p auto -b $BOARD ..
    # hack to prevent CI failure, QEMU build does not create .hex
    - if [ $BOARD == "qemu_cortex_m3" ] ; then touch build/zephyr/zephyr.hex ; fi
    # copy the build artifacts to the root directory
    - cp build/zephyr/zephyr.elf build/zephyr/zephyr.hex build/zephyr/.config ..
  parallel:
    matrix:
      - BOARD: [ nucleo_f767zi, hifive_premier_p550_mcu, qemu_cortex_m3 ]
  artifacts:
    paths:
      - zephyr.elf
      - zephyr.hex
      - .config

test:
  stage: test
  needs:
    - job: build
      artifacts: true
      parallel:
        matrix:
          - BOARD: qemu_cortex_m3
  before_script:
    - sudo apt-get -qq update && sudo apt-get install -qq telnet qemu-system-arm
  script:
    - python3 $CI_PROJECT_DIR/scripts/run_qemu_ci.py zephyr.elf
