stages:
  - build

# Use a pre-built Docker image that includes the Zephyr build environment.
image: zephyrprojectrtos/zephyr-build:latest

variables:
  ZEPHYR_WORKSPACE: zephyrproject

.zephyr_setup: &zephyr_setup_template
  # Common setup steps for any Zephyr job
  before_script:
    # 1. Initialize the west workspace from upstream Zephyr manifest
    - west init -m https://github.com/zephyrproject-rtos/zephyr --mr main $ZEPHYR_WORKSPACE
    - cd $ZEPHYR_WORKSPACE
    # 2. Update all modules defined in the manifest (e.g., zephyr, modules)
    - west update
    # 3. Export Zephyr's CMake package and set up the environment
    - west zephyr-export
    # 4. Create and activate the virtual environment
    - python3 -m venv .venv
    - source .venv/bin/activate
    - export ZEPHYR_BASE=$PWD/zephyr


build:
  stage: build
  <<: *zephyr_setup_template
  script:
    # -p auto: automatically handles pristine builds
    - west build -p auto -b $BOARD ..
    # copy the build artifacts to the root directory
    - cp build/zephyr/zephyr.elf build/zephyr/zephyr.hex build/zephyr/.config ..
  parallel:
    matrix:
      - BOARD: [ nucleo_f767zi, hifive_premier_p550_mcu ]
  artifacts:
    paths:
      - zephyr.elf
      - zephyr.hex
      - .config


