# Kernel options
CONFIG_INIT_STACKS=y

CONFIG_POSIX_API=y

# Logging
CONFIG_LOG=y
#CONFIG_LOG_DEFAULT_LEVEL=0
CONFIG_PRINTK=y
CONFIG_NET_LOG=y

# Generic networking options
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_ARP=y
CONFIG_NET_UDP=y
CONFIG_NET_TCP=y
CONFIG_ZVFS_POLL_MAX=8
CONFIG_NET_MAX_CONTEXTS=12
CONFIG_NET_MAX_CONN=16

# IP address options
CONFIG_NET_DHCPV4=y
CONFIG_NET_DHCPV4_OPTION_CALLBACKS=y
CONFIG_NET_CONFIG_AUTO_INIT=y
#CONFIG_DNS_RESOLVER=y # This makes telnet console hang?
# Hostname will be registered with DHCP so if the network supports it,
# it will be the DNS name too. UNIQUE=y appends a random UUID to the
# end of HOSTNAME, you will need to watch the console to get this, or
# give yourself a unique hostname.
CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_HOSTNAME_ENABLE=y
CONFIG_NET_HOSTNAME="stm32-bmc"
CONFIG_NET_HOSTNAME_UNIQUE=y
# default / no-DHCP IP address
#CONFIG_NET_CONFIG_MY_IPV4_ADDR="192.168.2.55"

# local/network shell
CONFIG_KERNEL_SHELL=y
#CONFIG_SHELL_TAB=y
CONFIG_NET_SHELL=y
CONFIG_SHELL_BACKEND_TELNET=y
CONFIG_SHELL_TELNET_SUPPORT_COMMAND=y

# GPIO options
CONFIG_GPIO=y

# HTTP Server
CONFIG_HTTP_SERVER=y
CONFIG_ZVFS_EVENTFD_MAX=4
CONFIG_JSON_LIBRARY=y

# TLS
CONFIG_MBEDTLS=y
CONFIG_MBEDTLS_BUILTIN=y
CONFIG_MBEDTLS_ENABLE_HEAP=y
CONFIG_MBEDTLS_HEAP_SIZE=20000
CONFIG_MBEDTLS_SSL_MAX_CONTENT_LEN=2048
CONFIG_NET_SOCKETS_SOCKOPT_TLS=y
CONFIG_NET_SOCKETS_TLS_MAX_CONTEXTS=4
CONFIG_TLS_CREDENTIALS=y
CONFIG_PSA_WANT_ALG_ECDH=y
CONFIG_PSA_WANT_ALG_ECDSA=y
CONFIG_PSA_WANT_ECC_SECP_R1_256=y
CONFIG_PSA_WANT_KEY_TYPE_ECC_PUBLIC_KEY=y
CONFIG_PSA_WANT_KEY_TYPE_ECC_KEY_PAIR_IMPORT=y
CONFIG_PSA_WANT_KEY_TYPE_ECC_KEY_PAIR_EXPORT=y
CONFIG_PSA_WANT_KEY_TYPE_ECC_KEY_PAIR_GENERATE=y
CONFIG_MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED=y
CONFIG_PSA_WANT_ALG_CCM=y
CONFIG_PSA_WANT_ALG_GCM=y
CONFIG_MBEDTLS_PK_WRITE_C=y
CONFIG_PSA_WANT_ALG_TLS12_PRF=y
CONFIG_PSA_WANT_ALG_SHA_1=y
CONFIG_PSA_WANT_ALG_SHA_256=y
CONFIG_PSA_CRYPTO=y
CONFIG_PSA_WANT_ALG_CHACHA20_POLY1305=y
CONFIG_PSA_WANT_KEY_TYPE_CHACHA20=y

# Gentoo mode
CONFIG_SPEED_OPTIMIZATIONS=y
