manifest:
  remotes:
    - name: zephyr
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyr
      revision: 5d653fcfd4f
      import: true

  self:
    path: wallabmc
