CONFIG_NET_IPV6=n
CONFIG_RTC=n
CONFIG_REDFISH=n
CONFIG_APP_WEB=n
CONFIG_APP_WEB_TERMINAL=n
CONFIG_PERSISTENT_STORAGE=n
CONFIG_TEST_RANDOM_GENERATOR=y
CONFIG_TEST_CSPRNG_GENERATOR=y
CONFIG_NET_IF_MAX_IPV4_COUNT=2
CONFIG_NET_IF_MAX_IPV6_COUNT=2
